# You need to change the setting depneding on your dataset.

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################

sampling_rate: &sampling_rate
    24000
fft_size: &fft_size
    1024
hop_size: &hop_size
    256
band_widths: &band_widths
    - 5
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 16
    - 16
    - 16
    - 16
    - 16
    - 16
    - 16
    - 16
    - 16
    - 16
    - 16
    - 16
    - 16
    - 16
    - 32
    - 32
    - 32
    - 32
    - 32
    - 32
    - 32

###########################################################
#         GENERATOR NETWORK ARCHITECTURE SETTING          #
###########################################################
generator_type: "BSRNN"
generator_params:
    sampling_rate: *sampling_rate
    fft_size: *fft_size
    hop_size: *hop_size
    band_widths: *band_widths
    num_channels: 128
    num_layers: 12


###########################################################
#                   STFT LOSS SETTING                     #
###########################################################
stft_loss_params:
    fft_sizes: [256, 512, 1024, 2048]
    hop_sizes: [64, 128, 256, 512]
    win_sizes: [256, 512, 1024, 2048]
    window: "hann_window"

###########################################################
#                       LOSS SETTING                      #
###########################################################
lambda_pcm: 200.0
lambda_mag: 1.0
lambda_spec: 1.0

###########################################################
#                  DATA LOADER SETTING                    #
###########################################################
batch_size: 8
batch_max_steps: 72000
reverb_rate: 0.25
vocal_mixup_rate: 0.0
noise_mixup_rate: 0.2
pin_memory: true
num_workers: 8

###########################################################
#             OPTIMIZER & SCHEDULER SETTING               #
###########################################################

generator_optimizer_type: "AdamW"
generator_optimizer_params:
    lr: 0.001
    betas: [0.8, 0.99]
    eps: 1.0e-9
    weight_decay: 0.01

generator_scheduler_type: "StepLR"
generator_scheduler_params:
    step_size: 100000
    gamma: 0.98
generator_grad_norm: 5

###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 1000000
save_interval_steps: 1000
eval_interval_steps: 10000
log_interval_steps: 1000

###########################################################
#                     OTHER SETTING                       #
###########################################################
num_save_intermediate_results: 8

